export type SceneId = 'world' | 'compute' | 'model' | 'block' | 'tools' | 'vision' | 'diffusion';
export type Evidence = 'Illustrative' | 'Observed' | 'Playback';
export interface Concept {
  id: string;
  title: string;
  short: string;
  scene: SceneId;
  category: string;
  description: string;
  input: string;
  output: string;
  deeper: string;
  sources: string[];
  enter?: SceneId;
  related: string[];
}
export const sources: Record<string, { title: string; url: string }> = {
  network: {
    title: 'MDN · How the web works',
    url: 'https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works',
  },
  tls: { title: 'IETF · TLS 1.3', url: 'https://www.rfc-editor.org/rfc/rfc8446' },
  gpu: {
    title: 'NVIDIA · CUDA programming guide',
    url: 'https://docs.nvidia.com/cuda/cuda-programming-guide/',
  },
  transformer: {
    title: 'Vaswani et al. · Attention Is All You Need',
    url: 'https://arxiv.org/abs/1706.03762',
  },
  llama: { title: 'Touvron et al. · LLaMA', url: 'https://arxiv.org/abs/2302.13971' },
  cache: {
    title: 'Hugging Face · How caching works',
    url: 'https://huggingface.co/docs/transformers/cache_explanation',
  },
  tokenizer: {
    title: 'Hugging Face · Tokenizer summary',
    url: 'https://huggingface.co/docs/transformers/tokenizer_summary',
  },
  mcp: {
    title: 'MCP · Architecture overview',
    url: 'https://modelcontextprotocol.io/docs/learn/architecture',
  },
  vision: { title: 'Hugging Face · LLaVA', url: 'https://huggingface.co/docs/transformers/model_doc/llava' },
  diffusion: {
    title: 'Hugging Face · Text-to-image diffusion',
    url: 'https://huggingface.co/docs/diffusers/using-diffusers/conditional_image_generation',
  },
  api: {
    title: 'OpenAI · Chat Completions reference',
    url: 'https://developers.openai.com/api/reference/resources/chat/subresources/completions/methods/create',
  },
};
const c = (
  id: string,
  title: string,
  short: string,
  scene: SceneId,
  category: string,
  description: string,
  input: string,
  output: string,
  deeper: string,
  refs: string[],
  related: string[] = [],
  enter?: SceneId,
): Concept => ({
  id,
  title,
  short,
  scene,
  category,
  description,
  input,
  output,
  deeper,
  sources: refs,
  related,
  enter,
});
export const concepts: Record<string, Concept> = Object.fromEntries(
  [
    c(
      'device',
      'Your device',
      'Every answer starts with a question.',
      'world',
      'THE REQUEST',
      'When you press Enter, the app collects your message and the conversation context it intends to send. It packages them into a request for a model service. Your browser handles the interface; the model may run elsewhere. This is the starting point of our journey. Select another object to explore freely, or play the guided route below.',
      'Your message + conversation',
      'An application request',
      'Think of the app as a letter writer: it prepares the content and destination. The analogy ends at the envelope—network software divides and transports bytes, and a single message is not a single packet. A local model can process the request on your device instead.',
      ['network'],
      ['router', 'context'],
    ),
    c(
      'router',
      'Wi-Fi & router',
      'The first hop out of your local network.',
      'world',
      'NETWORK',
      'Your device communicates with a nearby access point, often combined with a router. The router forwards traffic toward the destination network. It does not understand or tokenise your prompt. With HTTPS, application content is encrypted between the client and the service’s TLS endpoint; routing information still has to remain usable to deliver the traffic.',
      'Network traffic from your device',
      'Traffic toward the next network',
      'A signpost is a useful analogy: a router chooses where traffic goes next. It does not write the letter. Wi-Fi is only one possible connection; wired Ethernet and cellular networks work too. DNS lookup and connection setup may already be cached or established.',
      ['network', 'tls'],
      ['internet'],
    ),
    c(
      'internet',
      'Internet backbone',
      'Many networks cooperate to carry the request.',
      'world',
      'NETWORK',
      'The request travels across interconnected networks toward the service. We compress that infrastructure into a small network globe so the path stays readable. The highlighted line is a representative route, not a traceroute. Its length, speed and direction on this map are teaching choices, not a measurement of your connection.',
      'Encrypted application traffic',
      'Traffic arriving at service ingress',
      'A request can cross several administrative networks. Different messages may use different routes. The app can measure elapsed client time, but an ordinary model API does not reveal each router, geographic path or packet delay.',
      ['network'],
      ['datacenter'],
    ),
    c(
      'datacenter',
      'Data centre',
      'The physical home of a hosted model service.',
      'world',
      'INFRASTRUCTURE',
      'A data centre brings together servers, networking, power and cooling. A model service receives the request through its application infrastructure and assigns compute work. The building here represents that physical setting. It is not the actual location of a selected provider. Open the compute view to move from the building to the rack and accelerator.',
      'A request at the service boundary',
      'Work assigned to serving infrastructure',
      'Physical containment and logical flow are different: a rack sits inside a building, while scheduling is software. A warm model can already have its weights loaded. A new request does not imply a model download, a new server, or a fresh training run.',
      ['gpu', 'network'],
      ['ingress', 'rack', 'gpu'],
      'compute',
    ),
    c(
      'ingress',
      'Service ingress',
      'Network delivery becomes application work.',
      'compute',
      'SERVING',
      'At the service boundary, software receives and validates the application request. Authentication, limits, routing and scheduling can happen here. This is where our view changes from traffic forwarding to application handling. The next step is model execution, but this atlas cannot observe a provider’s actual queue or scheduling decision.',
      'Request body + credentials',
      'Validated work for the model service',
      'A reception desk is a limited analogy: it directs work to the appropriate service. Real deployments may spread these functions over many processes and machines. We show one compact system to explain the roles, not a universal deployment blueprint.',
      ['network'],
      ['context', 'rack'],
    ),
    c(
      'rack',
      'Server rack',
      'Power, networking and compute in one enclosure.',
      'compute',
      'HARDWARE',
      'A rack holds multiple servers and their connections. A server combines processors, memory, storage and often accelerators. The host software prepares inputs and launches model operations. The model is not a separate physical object inside the chassis; it is parameters and computation executed by this hardware.',
      'Scheduled work and model parameters',
      'Operations dispatched to compute devices',
      'This is a procedural miniature, with no vendor-specific dimensions or live resource readings. A large model may span several accelerators or servers; a smaller model may run on a single device. Rack count is a drawing choice.',
      ['gpu'],
      ['gpu'],
    ),
    c(
      'gpu',
      'GPU accelerator',
      'Parallel arithmetic turns model parameters into predictions.',
      'compute',
      'HARDWARE',
      'An accelerator performs the tensor operations used by a neural network. Model weights and working data move through its memory system while many arithmetic operations run in parallel. The host coordinates this work. Enter the model view to see the logical computation that this hardware executes—not literal rooms or layers inside the chip.',
      'Tensors + already loaded weights',
      'Computed tensor representations',
      'The board is a physical illustration; the model view is a mathematical one. This change of scale is a teaching transition. Inference applies learned parameters to inputs. Training is the separate process that adjusts those parameters, and is outside this journey.',
      ['gpu'],
      ['weights', 'context'],
      'model',
    ),
    c(
      'weights',
      'Model weights',
      'Learned parameters, available for inference.',
      'compute',
      'MODEL STORAGE',
      'Weights are numerical parameters learned during training. During inference they are used to transform the request’s representations. They are different from your conversation context, and ordinary chat requests do not update them. This memory bank simply represents storage accessible to compute.',
      'Parameters loaded by the serving system',
      'Parameter values for tensor operations',
      'Do not read the number of blocks as a memory capacity. The browser cannot inspect proprietary weights, actual device memory or memory bandwidth through a text API. Different quantisation formats and deployment strategies change storage requirements.',
      ['gpu'],
      ['gpu', 'context'],
    ),
    c(
      'context',
      'Context preparation',
      'The model sees the messages the app actually sends.',
      'model',
      'PREPARE',
      'The application chooses the conversation, instructions and optional tool results for the next model call. These inputs have to fit the model’s context limits. The conversation you see and the context the application sends are not automatically the same. In this explorer, live requests include up to four complete previous live exchanges plus your new message, within a visible character budget.',
      'Instructions + bounded conversation',
      'Formatted model input',
      'Context is temporary input, not permanent model memory. A provider’s chat template adds role and formatting tokens. Our teaching token display encodes only the text shown in the input box; it is not an estimate of the full billed prompt.',
      ['tokenizer', 'api'],
      ['tokenizer'],
    ),
    c(
      'tokenizer',
      'Tokenisation',
      'Text becomes a sequence of vocabulary identifiers.',
      'model',
      'PREPARE',
      'A real tokenizer maps text to identifiers in the vocabulary used by its model. Pieces can include spaces, punctuation or parts of words. For a reproducible teaching example, this explorer uses a toy UTF-8 byte tokenizer: each byte value is an ID from 0 to 255. It preserves Chinese, emoji and whitespace, but is not BPE and does not report provider token IDs or billable token counts.',
      'Text encoded as UTF-8',
      'Toy byte IDs (0–255)',
      'Try mixed-language text in Chat and inspect the Data tab. One visible character can occupy several bytes. Real tokenizers merge or segment units according to a specific trained vocabulary, so their token counts and IDs will differ.',
      ['tokenizer'],
      ['embedding'],
    ),
    c(
      'embedding',
      'Embeddings & position',
      'Identifiers become vectors that computation can use.',
      'model',
      'REPRESENT',
      'The model looks up learned vector representations for token IDs. Position information lets the computation distinguish order. Here a small grid stands in for a much wider numerical representation. Its colours are illustrative; they are not measured activations or a map of what the model is thinking.',
      'Token identifiers and positions',
      'Position-aware representations',
      'In the LLaMA-style block used as a reference here, rotary position information is applied to queries and keys in attention. We group position with the representation stage for orientation; we do not imply that every architecture simply adds a positional vector to an embedding.',
      ['llama'],
      ['prefill', 'attention'],
    ),
    c(
      'prefill',
      'Prompt prefill',
      'Process the prompt before generating the next token.',
      'model',
      'PREFILL',
      'The model processes the prompt through its transformer stack. Causal masking prevents a position from attending to future positions. Operations across prompt positions can be parallelised within layers, while the layers still depend on earlier layers. The final prompt position supplies the representation used to predict the next token.',
      'Prompt representations',
      'Next-token scores + reusable keys and values',
      'Our stack has six visible blocks for readability. That is not the layer count of your selected model. The same basic stack is used during decoding, but then new token positions are added over repeated passes.',
      ['transformer', 'cache'],
      ['block', 'cache', 'sampling'],
    ),
    c(
      'block',
      'Transformer block',
      'Attention and a feed-forward network refine representations.',
      'model',
      'TRANSFORM',
      'A transformer repeats a block of operations. This teaching block follows a pre-normalised decoder layout: normalise, attend, add a residual; normalise, apply the MLP, add a residual. Open the block to separate these operations in space. The repeated stack is logical computation, not a collection of physical chips.',
      'Hidden representations',
      'Refined hidden representations',
      'Our representative ordering follows the LLaMA family, with RMS normalisation, rotary attention and a gated feed-forward network. Exact dimensions, head counts and layer counts vary. The residual path adds a sublayer’s output back to its input.',
      ['llama'],
      ['norm', 'attention', 'mlp', 'residual'],
      'block',
    ),
    c(
      'cache',
      'KV cache',
      'Reuse past keys and values at each attention layer.',
      'model',
      'REUSE',
      'During generation, a layer can retain keys and values for positions already processed. New queries attend to those retained values together with the new position. This avoids recomputing past key and value projections. The small bank beside each layer grows in our decode illustration.',
      'Past per-layer keys and values',
      'Reused context for the new position',
      'A KV cache is neither a finished-answer store nor a vector database. The growing bank is a teaching example, not actual memory telemetry. Cache policies vary: some have fixed capacity or retain a sliding window.',
      ['cache'],
      ['attention', 'decode'],
    ),
    c(
      'sampling',
      'Projection & sampling',
      'Scores become a choice for the next token.',
      'model',
      'CHOOSE',
      'A final normalisation and vocabulary projection turn the last representation into logits: one score per vocabulary entry. A decoding strategy chooses the next token. Try our synthetic five-token distribution in the Data tab. Temperature changes its concentration; at zero, our experiment explicitly chooses the highest score.',
      'Vocabulary logits',
      'One selected token identifier',
      'The experiment uses stable softmax and a repeatable random seed. It does not affect an already received reply. API logprobs, when available in Chat, are a separate observed dataset; a returned top-k list is only part of a distribution and is never renormalised here.',
      ['transformer', 'api'],
      ['decode'],
    ),
    c(
      'decode',
      'Autoregressive decode',
      'Append a token. Run the next prediction. Repeat.',
      'model',
      'DECODE',
      'The chosen token becomes part of the context for the following prediction. The model executes another pass for the new position, reusing cached keys and values where supported. This loop continues until a stopping condition is reached. The growing ribbon below is a scripted illustration of successive output pieces.',
      'A new token + preceding context',
      'The next prediction',
      'Our timeline repeats this stage so you can see context grow. Its timing is deliberate playback, not tokens per second. Network stream events can contain multiple tokens, parts of text, or metadata; a received network chunk is not inherently one model token.',
      ['cache', 'api'],
      ['response'],
    ),
    c(
      'response',
      'The response returns',
      'Generated text becomes the answer you can read.',
      'world',
      'RETURN',
      'Output token IDs are decoded into text and the service sends the result back to the application. Some endpoints stream incremental events; others return one final response. The browser assembles received text and updates the conversation. Our highlighted return path shows the direction of the response, not actual packets or measured latency.',
      'Received text events or final output',
      'The answer in your conversation',
      'Live mode labels client-observed receipt separately from teaching playback. Pausing the journey pauses the illustration only. Stop aborts the local request where possible; it cannot guarantee that a remote provider has stopped computation or billing.',
      ['api'],
      ['device'],
    ),
    c(
      'norm',
      'Normalisation',
      'Keep representation scales controlled before each sublayer.',
      'block',
      'TRANSFORMER · 01',
      'In this pre-normalised example, RMSNorm rescales a representation before attention and again before the feed-forward sublayer. Learned scale parameters remain part of the model. Normalisation is a numerical operation, not an interpretation of the user’s intent.',
      'A hidden vector',
      'A rescaled vector',
      'The expanded view follows x → attention(RMSNorm(x)) + x, then h → MLP(RMSNorm(h)) + h. This ordering is architecture-specific; other transformer families place normalisation differently.',
      ['llama'],
      ['attention', 'residual'],
    ),
    c(
      'attention',
      'Causal self-attention',
      'Each position gathers information from allowed positions.',
      'block',
      'TRANSFORMER · 02',
      'Queries and keys produce compatibility scores; masked, normalised scores weight the values. Multiple heads provide different learned projections. The Data tab shows a small synthetic causal matrix. The blank upper triangle represents future positions that cannot be read.',
      'Queries, keys and values',
      'Weighted combinations of values',
      'Attention(Q,K,V) = softmax(QKᵀ / √d + causal mask)V. The plotted numbers are invented for teaching. Attention weights alone are not a faithful account of hidden reasoning, intent or why an answer was produced.',
      ['transformer'],
      ['cache', 'mlp'],
    ),
    c(
      'mlp',
      'MLP · feed-forward',
      'A learned nonlinear transformation inside every block.',
      'block',
      'TRANSFORMER · 03',
      'The multilayer perceptron applies learned transformations to each position’s representation. In our reference family it uses a gated feed-forward form. It complements attention inside the same block. MLP is a neural-network sublayer; MCP is an application protocol you can explore in the tool scenario.',
      'A normalised hidden representation',
      'A transformed representation',
      'The node fan-out illustrates expansion and contraction, not individual neurons or parameters from an actual model. Position-wise computation still depends on representations already shaped by attention.',
      ['llama'],
      ['residual', 'mcp'],
    ),
    c(
      'residual',
      'Residual pathway',
      'Carry the input forward and add a learned update.',
      'block',
      'TRANSFORMER · 04',
      'A residual connection adds a sublayer’s output to its input. In the expanded block, the outside route bypasses attention and then the MLP to show these additions. This lets each sublayer modify an existing representation rather than replacing it entirely.',
      'Original representation + sublayer output',
      'Their element-wise sum',
      'The bypass is a mathematical addition, not a second network request. The spatial gap is controlled by the Explode slider and has no physical meaning.',
      ['llama'],
      ['block'],
    ),
    c(
      'intent',
      'Tool-call intent',
      'The model proposes an action for the host.',
      'tools',
      'TOOL USE · 01',
      'In this simulated calculator story, a model response proposes a multiply operation with arguments 24 and 7. The model does not execute that tool itself. The application receives the proposed call and decides how to handle it. Ordinary text generation need not use any tool.',
      'Question: “What is 24 × 7?”',
      'Proposed call: multiply(24, 7)',
      'This trace is deterministic and does not come from a model. In a real application the host validates arguments, applies permissions and may request approval before running a tool.',
      ['mcp'],
      ['host'],
    ),
    c(
      'host',
      'Application host',
      'Coordinates the model and external capabilities.',
      'tools',
      'TOOL USE · 02',
      'The host owns the interaction and coordinates tool access. In this example it passes the requested operation to an MCP client. MCP describes communication between the client and a server exposing capabilities. Tool calls can also use other integration mechanisms.',
      'A proposed tool operation',
      'A validated operation passed to the client',
      'The host is application software, outside the transformer. Our host runs a bundled calculator fixture with fixed arguments; it never connects to external accounts.',
      ['mcp'],
      ['mcp'],
    ),
    c(
      'mcp',
      'MCP client & server',
      'A protocol boundary between an app and a tool service.',
      'tools',
      'TOOL USE · 03',
      'A client communicates with an MCP server that exposes tools. The server handles a request and returns a result. Here the simulated server exposes multiplication. The connector is labelled communicates with, because it is a protocol relationship rather than physical containment or a neural layer.',
      'Tool name and arguments',
      'Tool result: 168',
      'The two small units represent separate roles, not necessarily two physical machines. No real MCP connection is made in this demo.',
      ['mcp'],
      ['tool-result', 'mlp'],
    ),
    c(
      'tool-result',
      'Result back to context',
      'A second model step can use the tool’s output.',
      'tools',
      'TOOL USE · 04',
      'The calculator returns 168. The host adds that result to the conversation associated with the tool call, then requests another model step. Our scripted final response uses that value. This loop is optional application orchestration, distinct from the token-by-token decode loop inside a model.',
      'Calculator result: 168',
      'Sample response: “24 × 7 = 168.”',
      'A real host must connect the result to the appropriate call. Here the trace displays the fixture arguments and result directly so you can follow the sequence without API credentials.',
      ['mcp'],
      ['context'],
    ),
    c(
      'image',
      'Image input',
      'Pixels join the request alongside text.',
      'vision',
      'VISION · 01',
      'Our bundled landscape is a small non-human fixture. An image-understanding system prepares pixels before turning them into representations the language model can use. The image and the question travel through the same application boundary as a text request, but the input representation is richer.',
      'Landscape pixels + “What is in this image?”',
      'Prepared visual input',
      'The fixture is drawn locally and never uploaded. Selecting this scenario plays a scripted explanation, not a real image-analysis request.',
      ['vision'],
      ['patches'],
    ),
    c(
      'patches',
      'Visual patches & encoder',
      'Image regions become learned visual features.',
      'vision',
      'VISION · 02',
      'In a representative vision-transformer path, the prepared image is divided into patches and processed by a vision encoder. The separated tiles make that change of representation visible. They are an illustration of image regions, not a dump of a model’s intermediate tensors.',
      'Prepared image regions',
      'Visual feature vectors',
      'We use a LLaVA-style path to show a vision encoder and a connector to language embeddings. Architectures vary. A convolutional network is not a mandatory stage of every multimodal model.',
      ['vision'],
      ['fusion'],
    ),
    c(
      'fusion',
      'Vision meets language',
      'Visual features become usable language-model context.',
      'vision',
      'VISION · 03',
      'A learned connector maps visual features into a form usable by the language model. Combined with the text prompt, this context supports text generation. Our sample answer describes mountains, water and a sun in the bundled scene.',
      'Visual features + text representations',
      'Context for a language-model response',
      'The bridge is representative, not universal: other models combine modalities differently. The coloured bars and sample answer are fixtures. No actual image embeddings or attention maps are observed.',
      ['vision'],
      ['prefill'],
    ),
    c(
      'conditioning',
      'Text conditioning',
      'The prompt guides a representative diffusion process.',
      'diffusion',
      'IMAGE GENERATION · 01',
      'An image-generation pipeline can encode a text description into conditioning representations. In this latent-diffusion-style story, those representations guide iterative denoising. This is a different generation process from the language model’s next-token loop.',
      '“A quiet mountain lake at sunrise”',
      'Text conditioning representations',
      'Latent diffusion is one family of image-generation methods. These frames are synthetic visual fixtures; they do not reveal how a particular commercial image model works.',
      ['diffusion'],
      ['noise'],
    ),
    c(
      'noise',
      'Initial latent noise',
      'Begin from a seeded noisy representation.',
      'diffusion',
      'IMAGE GENERATION · 02',
      'Our illustration starts with repeatable noise. In a latent diffusion system, iterative work happens in a compressed representation rather than directly in full-resolution pixels. The noisy tile here is a visual stand-in for that latent.',
      'Seeded noise',
      'A starting latent representation',
      'A latent is a numerical representation, not necessarily a small viewable photograph. We make it visible as a tile to support the walkthrough; the displayed texture is not a genuine model state.',
      ['diffusion'],
      ['denoise'],
    ),
    c(
      'denoise',
      'Iterative refinement',
      'Repeat a conditioned denoising step.',
      'diffusion',
      'IMAGE GENERATION · 03',
      'The pipeline uses a denoising network and a scheduler over repeated steps, guided by the conditioning. Seek along the timeline to compare our fixture frames. The landscape gradually appears to communicate refinement; the browser is not executing a diffusion model.',
      'Current latent + conditioning + step',
      'Updated latent',
      'The number of visible frames is chosen for teaching. It is not a recommended inference-step count or a quality measurement. Playback speed changes only how quickly this illustration advances.',
      ['diffusion'],
      ['image-output'],
    ),
    c(
      'image-output',
      'Decode to an image',
      'Convert the refined representation into pixels.',
      'diffusion',
      'IMAGE GENERATION · 04',
      'A decoder converts the final latent representation into an image. Our endpoint is the same bundled mountain landscape used in the vision story, which lets you compare understanding an existing image with generating a new one.',
      'A refined latent representation',
      'A viewable image',
      'The final image is locally authored fixture art, not an AI-generated result. No paid endpoint or large model is needed to explore this branch.',
      ['diffusion'],
      ['response'],
    ),
  ].map((item) => [item.id, item]),
);

export const sceneNames: Record<SceneId, string> = {
  world: 'Request journey',
  compute: 'Inside the data centre',
  model: 'Inside the model',
  block: 'Transformer block',
  tools: 'Tools & MCP',
  vision: 'Understanding an image',
  diffusion: 'Generating an image',
};
export const sceneParents: Partial<Record<SceneId, SceneId>> = {
  compute: 'world',
  model: 'compute',
  block: 'model',
  tools: 'model',
  vision: 'model',
  diffusion: 'world',
};
export const sceneEntries: Record<SceneId, string> = {
  world: 'device',
  compute: 'rack',
  model: 'prefill',
  block: 'attention',
  tools: 'intent',
  vision: 'image',
  diffusion: 'conditioning',
};
export const relationships: {
  from: string;
  to: string;
  kind: 'contains' | 'executes' | 'communicates-with' | 'transforms';
}[] = [
  { from: 'datacenter', to: 'rack', kind: 'contains' },
  { from: 'rack', to: 'gpu', kind: 'contains' },
  { from: 'gpu', to: 'block', kind: 'executes' },
  { from: 'block', to: 'attention', kind: 'contains' },
  { from: 'block', to: 'mlp', kind: 'contains' },
  { from: 'device', to: 'router', kind: 'communicates-with' },
  { from: 'router', to: 'internet', kind: 'communicates-with' },
  { from: 'host', to: 'mcp', kind: 'communicates-with' },
  { from: 'tokenizer', to: 'embedding', kind: 'transforms' },
  { from: 'patches', to: 'fusion', kind: 'transforms' },
];
export interface Scenario {
  id: string;
  name: string;
  subtitle: string;
  prompt: string;
  answer: string;
  steps: string[];
}
const outbound = ['device', 'router', 'internet', 'datacenter', 'ingress', 'rack', 'gpu'];
export const scenarios: Record<string, Scenario> = {
  text: {
    id: 'text',
    name: 'Text conversation',
    subtitle: 'From your first word to the next token.',
    prompt: 'Why is the sky blue?',
    answer:
      'Sunlight contains many colours. Air molecules scatter shorter blue wavelengths more strongly than red wavelengths, so blue light reaches your eyes from across the sky.',
    steps: [
      ...outbound,
      'context',
      'tokenizer',
      'embedding',
      'prefill',
      'block',
      'cache',
      'sampling',
      'decode',
      'decode',
      'decode',
      'response',
    ],
  },
  tools: {
    id: 'tools',
    name: 'Use a tool',
    subtitle: 'A model, an application, and a calculator.',
    prompt: 'What is 24 × 7?',
    answer: '24 × 7 = 168.',
    steps: [...outbound, 'context', 'intent', 'host', 'mcp', 'tool-result', 'decode', 'response'],
  },
  vision: {
    id: 'vision',
    name: 'Understand an image',
    subtitle: 'From pixels to a language-model context.',
    prompt: 'What is in this image?',
    answer: 'The sample image shows layered mountains, a calm lake and a small sun above the horizon.',
    steps: [...outbound, 'image', 'patches', 'fusion', 'prefill', 'decode', 'response'],
  },
  diffusion: {
    id: 'diffusion',
    name: 'Generate an image',
    subtitle: 'A guided illustration of latent diffusion.',
    prompt: 'A quiet mountain lake at sunrise',
    answer:
      'Illustrative image complete: a quiet mountain lake at sunrise. This is bundled fixture art, not an image generated by a model.',
    steps: [
      ...outbound,
      'conditioning',
      'noise',
      'denoise',
      'denoise',
      'denoise',
      'image-output',
      'response',
    ],
  },
};
