import { scenarios, sources } from './content.ts';
import { icon } from './icons.ts';
import { palettes } from './theme.ts';
import { defaultGridIntensity } from './grid.ts';
export const shell = `
<header class="masthead"><a class="identity" href="#" id="home"><span class="brand-mark">${icon('cube')}</span><span><span class="eyebrow">AN INTERACTIVE AI ATLAS</span><span class="brand-title">LLM Inference Explorer <span class="version">3D</span></span></span></a><div class="header-controls"><label class="scenario-control"><span class="eyebrow">EXPLORE A SCENARIO</span><select id="scenario" aria-label="Scenario">${Object.values(
  scenarios,
)
  .map((s) => `<option value="${s.id}">${s.name}</option>`)
  .join(
    '',
  )}</select></label><button class="search-trigger" id="search-open">${icon('search')}<span>Find a concept</span><kbd>/</kbd></button><button class="icon-button" id="appearance-open" aria-label="Colour palette" title="Colour palette">${icon('palette')}</button><button class="icon-button" id="theme" aria-label="Toggle dark theme">${icon('sun')}</button><button class="icon-button" id="settings-open" aria-label="Settings">${icon('settings')}</button></div></header>
<header class="scene-intro" aria-label="Current scene"><nav id="breadcrumbs" aria-label="Scene breadcrumbs"></nav><h1 id="scene-title"></h1><p id="scene-subtitle"></p></header><main id="atlas-main"><div id="scene-framing" class="viewport scene-framing" aria-hidden="true"></div><div id="viewport" class="viewport"><div class="loading-scene">Building your atlas…</div></div><div id="fallback" class="fallback" hidden><h2>Explore the journey in 2D</h2><p>3D rendering is unavailable. Every stage and explanation is still accessible.</p><div id="fallback-stages"></div></div>
<div class="mobile-controls"><button id="mobile-journey">${icon('list')} Journey</button><button id="mobile-inspector">${icon('info')} Inspector</button></div>
<aside class="panel journey-panel" id="journey-panel" aria-label="Journey and chat"><div class="panel-heading"><div class="tabs" role="tablist" aria-label="Left panel"><button role="tab" aria-selected="true" id="journey-tab">${icon('list')} Journey</button><button role="tab" aria-selected="false" id="chat-tab">${icon('chat')} Chat</button></div><button class="small-icon" id="collapse-journey" aria-label="Collapse journey panel">${icon('minus')}</button></div>
<div id="journey-content"><div class="panel-section journey-summary"><span class="eyebrow">FOLLOW THE REQUEST</span><h2 id="journey-name"></h2><p id="journey-description"></p><label class="route-choice"><span>Compute route</span><select id="route" aria-label="Illustrative compute route"><option value="remote">Cloud service</option><option value="local">On this device</option></select></label></div><nav id="stages" aria-label="Journey stages"></nav><div class="journey-bottom"><span><i class="dot teal"></i><span id="stage-count"></span> stages to explore</span></div></div>
<div id="chat-content" hidden><div class="panel-section"><div class="mode-row"><h2>Try a request</h2><select id="mode" aria-label="Chat mode"><option value="demo">Demo</option><option value="live">Live API</option></select></div><p id="mode-note">Scripted sample responses. No account or API key needed.</p><button class="example" id="example"></button></div><div id="messages" class="messages" aria-label="Conversation"></div><div class="chat-compose"><form id="chat-form"><label class="sr-only" for="prompt">Your message</label><textarea id="prompt" maxlength="6000" rows="3" placeholder="Ask a question, then explore its journey…"></textarea><div class="compose-actions"><button type="button" class="text-button" id="clear-chat">Clear chat</button><button type="button" class="small-icon" id="stop-request" aria-label="Stop request" hidden>${icon('stop')}</button><button class="send-button" id="send" type="submit">Run demo ${icon('send')}</button></div></form><p id="request-status" role="status">Ready to explore</p><details class="context-details"><summary>Context & received data</summary><div id="received-data"></div></details></div></div></aside>
<button class="panel-restore" id="restore-journey" hidden>${icon('list')} Journey & chat</button>
<aside class="panel inspector-panel" id="inspector-panel" aria-label="Concept inspector"><div class="inspector-top"><span class="eyebrow">CONCEPT INSPECTOR</span><button class="small-icon" id="collapse-inspector" aria-label="Collapse inspector">${icon('minus')}</button></div><div id="inspector-header"></div><div class="inspector-tabs tabs" role="tablist" aria-label="Inspector"><button role="tab" id="learn-tab" aria-selected="true">Learn</button><button role="tab" id="data-tab" aria-selected="false">Data</button><button role="tab" id="sources-tab" aria-selected="false">Sources</button></div><div id="inspector-body" tabindex="0" role="region" aria-label="Concept reference"></div><div class="inspector-footer"><span class="evidence"><i class="dot teal"></i> Illustrative</span><span>Explore, then go deeper.</span></div></aside><button class="panel-restore inspector-restore" id="restore-inspector" hidden>${icon('info')} Inspector</button>
<div class="viewport-toolbar" aria-label="Camera controls">${[
  ['reset-camera', 'replay', 'Reset camera'],
  ['focus-selection', 'focus', 'Focus selection'],
  ['toggle-labels', 'labels', 'Toggle object labels'],
]
  .map(
    ([id, glyph, label]) =>
      `<button class="icon-button" id="${id}" aria-label="${label}" title="${label}" ${id === 'toggle-labels' ? 'aria-pressed="true"' : ''}>${icon(glyph)}</button>`,
  )
  .join('')}</div>
<div class="scene-tools"><div id="scene-switcher" aria-label="Explore scales"><button data-scene="world" class="active">Overview</button><button data-scene="compute">Hardware</button><button data-scene="model">Model</button><button data-scene="block">Block</button></div><label class="explode-control" id="explode-control" hidden>Explode block <input type="range" id="explode" min="0" max="100" value="65" aria-label="Explode transformer block"><output id="explode-value">65%</output></label></div>
<section class="playback panel" aria-label="Teaching playback"><div class="playback-top"><span class="evidence"><i class="dot teal"></i> TEACHING REPLAY</span><span id="playback-position"></span><label class="journey-mode">Mode <select id="journey-mode" aria-label="Journey mode"><option value="MANUAL">Manual</option><option value="AUTO" selected>Auto</option></select></label><button id="start-tour" class="text-button">Start journey ${icon('next')}</button><button id="stop-tour" class="text-button" hidden>Stop journey ${icon('stop')}</button><button id="resume-focus" class="text-button resume-focus" hidden title="Return to the current journey subject and restore guided zoom">${icon('focus')} Resume focus</button></div><div class="playback-controls"><button class="small-icon" id="previous" aria-label="Previous stage">${icon('back')}</button><button class="play-button" id="play" aria-label="Play journey">${icon('play')}</button><button class="small-icon" id="next" aria-label="Next stage">${icon('next')}</button><div class="timeline-wrap"><div class="timeline-heading"><label id="current-stage" for="timeline"></label><span class="guidance-status" id="guidance-status" role="status">Free exploration</span></div><input type="range" id="timeline" min="0" max="17" step="1" value="0" aria-label="Journey timeline"></div><select id="speed" aria-label="Playback speed" title="Teaching pace, not inference speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select><button class="small-icon" id="replay" aria-label="Replay journey">${icon('replay')}</button></div></section><div class="canvas-caption" id="canvas-caption"></div></main>
<footer class="footer"><span class="navigation-hints">Drag to orbit <b>·</b> Scroll to zoom <b>·</b> Right-drag to pan</span><div class="legend"><span><i class="dot teal"></i> Illustrative</span><span><i class="dot blue"></i> Observed</span><span><i class="dot gray"></i> Playback</span></div><button id="about-open" class="text-button">Sources & credits ${icon('expand')}</button></footer>
<dialog id="appearance-dialog" aria-labelledby="appearance-title"><div class="dialog-top"><div><span class="eyebrow">MAKE THE ATLAS YOURS</span><h2 id="appearance-title">Colour & appearance</h2></div><button data-close="appearance-dialog" class="small-icon" aria-label="Close appearance">${icon('close')}</button></div><p>Choose an accent family. Your palette works in both light and dark mode.</p><fieldset class="palette-options"><legend class="sr-only">Palette</legend>${palettes.map((p) => `<label class="palette-option"><input type="radio" name="palette" value="${p.id}"><span class="palette-swatch" style="--swatch:${p.accent};--companion:${p.companion}"></span><span>${p.name}</span></label>`).join('')}<label class="palette-option"><input type="radio" name="palette" value="custom"><span class="palette-swatch custom-swatch"></span><span>Custom accent</span></label></fieldset><div id="custom-colour-fields" hidden>
<div class="colour-picker-heading"><span>Custom accent</span><span class="colour-axis-hint">Choose a shade</span></div>
<div id="colour-plane" class="colour-plane" role="group" aria-label="Colour selection area" aria-describedby="colour-plane-help">
<input class="sr-only colour-axis" id="colour-saturation" type="range" min="0" max="100" step="1" aria-label="Saturation" aria-describedby="colour-plane-help">
<input class="sr-only colour-axis" id="colour-brightness" type="range" min="0" max="100" step="1" aria-label="Brightness" aria-describedby="colour-plane-help">
<span class="colour-thumb" aria-hidden="true"></span><span class="colour-key-hint" aria-hidden="true"></span></div>
<p id="colour-plane-help" class="sr-only">Drag to choose a shade. Tab between saturation and brightness; arrow keys adjust each value. Home and End reach its minimum and maximum.</p>
<div class="colour-hue-row"><label for="colour-hue">Hue</label><input id="colour-hue" type="range" min="0" max="360" step="1"></div>
<div class="custom-colour-row"><span id="colour-preview" class="colour-preview" role="img" aria-label="Selected accent"></span><label class="sr-only" for="custom-hex">Accent hex colour</label><input id="custom-hex" type="text" aria-label="Accent hex colour" maxlength="7" pattern="#[0-9a-fA-F]{6}" spellcheck="false" autocomplete="off" aria-describedby="custom-hex-error"><span class="colour-readable-preview" role="img" aria-label="Readable accent preview" title="Readable accent preview">Aa</span></div>
<p id="custom-hex-error" class="small error" role="status" hidden>Enter a six-digit HEX colour, such as #397e68.</p>
<p class="small">Text and surface shades adapt automatically for readable contrast.</p></div>
<div class="appearance-footer"><span>Changes apply immediately and save automatically on this device.</span></div></dialog>
<dialog id="search-dialog" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">Explore a concept</h2><button data-close="search-dialog" class="small-icon" aria-label="Close search">${icon('close')}</button></div><div class="search-input-wrap">${icon('search')}<input id="search-input" type="search" placeholder="Try “KV cache”, “GPU” or “MCP”…" aria-label="Search concepts" autocomplete="off"></div><div id="search-results"></div><div class="dialog-hint">Enter opens the first result · Tab explores results · Esc closes</div></dialog>
<dialog id="settings-dialog" aria-labelledby="settings-title"><div class="dialog-top"><div><span class="eyebrow">MAKE THE ATLAS YOURS</span><h2 id="settings-title">Settings</h2></div><button data-close="settings-dialog" class="small-icon" aria-label="Close settings">${icon('close')}</button></div><section class="display-settings" aria-labelledby="display-title"><h3 id="display-title">Display</h3><label class="check-row"><input id="ground-grid" type="checkbox" checked> Show ground grid</label><div class="grid-intensity-control"><label for="grid-intensity">Grid intensity</label><output id="grid-intensity-value" for="grid-intensity">${defaultGridIntensity}%</output><input id="grid-intensity" type="range" min="0" max="100" step="1" value="${defaultGridIntensity}" aria-describedby="display-save-note"></div><div class="grid-intensity-control dark-appearance-control"><label for="dark-appearance">Dark appearance</label><output id="dark-appearance-value" for="dark-appearance">Default</output><p class="small" id="dark-appearance-description">Adjust how deep the background appears in dark mode.</p><input id="dark-appearance" type="range" min="0" max="100" step="1" value="0" aria-describedby="dark-appearance-description dark-appearance-mode-note display-save-note"><span>Softer</span><span class="range-end">Deeper</span></div><p class="small" id="dark-appearance-mode-note">Available in dark mode. Your preference is kept in light mode.</p><p class="small" id="display-save-note">Display changes apply immediately and save automatically on this device.</p></section><h3 class="connection-title">Model connection</h3><p>Use a Chat Completions compatible endpoint. Changes apply with Save connection. Credentials stay in this tab’s memory; safe settings are saved on this device.</p><form id="settings-form"><label for="provider-url">Base URL</label><input id="provider-url" type="url" required placeholder="https://api.openai.com/v1"><label for="provider-model">Model identifier</label><input id="provider-model" required placeholder="Your provider’s model identifier" autocomplete="off"><label for="provider-key">API key <span class="muted">· optional for local services</span></label><input id="provider-key" type="password" autocomplete="off" placeholder="Kept in memory only"><label class="check-row"><input id="provider-stream" type="checkbox" checked> Request streaming</label><label class="check-row"><input id="provider-logprobs" type="checkbox"> Request token logprobs (if supported)</label><p class="small">Requests go directly from this browser to your endpoint. Browser access depends on its CORS policy. A rejected capability is shown as an error; the app never silently retries an answer request.</p><p id="settings-error" class="error" role="alert"></p><div class="dialog-actions"><button type="button" data-close="settings-dialog">Cancel</button><button class="primary" type="submit">Save connection</button></div></form></dialog>
<dialog id="about-dialog" aria-labelledby="about-title"><div class="dialog-top"><h2 id="about-title">A little curiosity, made spatial.</h2><button data-close="about-dialog" class="small-icon" aria-label="Close credits">${icon('close')}</button></div><p>LLM Inference Explorer by <a href="https://github.com/jonathankek1016" target="_blank" rel="noreferrer">Jonathan Kek</a>. Built around a simple question: “What happens after I press Enter?”</p><p>Born from an infrastructure and cybersecurity background, this personal learning project connects familiar hardware to the computation behind an AI response.</p><div class="about-evidence"><p><strong>Illustrative</strong> · Procedural scenes, assumed routes, synthetic distributions, tool/image fixtures.</p><p><strong>Observed</strong> · Captured input, actual API response, returned usage/logprobs and client receipt times.</p><p><strong>Playback</strong> · The timeline, motion and deliberate teaching pace.</p></div><p>Scene geometry and image fixtures are authored in code. The reference inspired the interface only. No hidden reasoning, proprietary activations or real hardware telemetry is exposed.</p><div class="source-list">${Object.values(
  sources,
)
  .map((s) => `<a href="${s.url}" target="_blank" rel="noreferrer">${s.title} ${icon('expand')}</a>`)
  .join(
    '',
  )}</div><p class="small">MIT licence · © 2026 jonathankek1016</p></dialog><div id="toast" role="status" hidden></div>`;
